### ISSUE TITLE
Print CSS ain't work

### ISSUE THREAD

**Issue by vovkkk** [litewrite/litewrite#126]
Yesteday I left comments in #113 but it seems unnoticed, so I open a new issue.

Current impementation has a few problems: basically it doesn't work in Firefox.
We of course can stick with display:none but to make it work in Fx demand to use some nasty tricks/hacks which will make code complicated.

I garantee that I spend not one hour to test defferent kinds of css and read many topics about printing in browsers and specifically in Fx; and it seems that opacity:0 is most simple and conveniet way in case of Litewrite.

Speaking about entries which was remain: this is because code in actual commit was different than one in my comment.

So again here is css that works in Firefox and Chromium as it should:

``` css
@media print {
    .aside, .entries, .menu-button, footer, #remotestorage-connect {
        opacity: 0;
    }
    body, .editor {
        margin: 0;
        padding: 0;
        height: auto;
        width: auto;
        position: static;
    }
}
```

Please, fix it.
